projects:
  Auction:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        graphQLApiId: u6qynf77prb4do3evr5nmgup3u
      endpoints:
        prod: >-
          https://tqtjn7bzbjc4bezgwokei4o36m.appsync-api.us-west-2.amazonaws.com/graphql
