projects:
  AuthAuction:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        graphQLApiId: zyuv6pl6l5eo3luhhyd26w4x5u
      endpoints:
        prod: >-
          https://v4f4cncc7zarjng4mwrsvjxbam.appsync-api.us-west-2.amazonaws.com/graphql
