// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://v4f4cncc7zarjng4mwrsvjxbam.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-west-2:f192fded-976a-4893-b93c-84e9c74703d3",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_bcOJ3Exrt",
    "aws_user_pools_web_client_id": "1hujcrgvj0fhoehrdv948720qo"
};


export default awsmobile;
